[tool.poetry]
package-mode = false
name = "MLOps-Project"
version = "0.1.0"
description = "MLOps project"
authors = ["Palandr123 <palandr545@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dvc = "^3.51.2"
dvc-gdrive = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
