model_name: bagging
artifact_path: bagging_model

tag_key: "model"
tag_value: "bagging Regressor"

module_name: "sklearn.ensemble"
class_name: "BaggingRegressor"

params:
  n_estimators: [10, 50, 100]
  max_samples: [0.5, 0.75, 1.0]
  max_features: [0.5, 0.75, 1.0]