model_name: gradient_boosting
artifact_path: gradient_boosting_model

tag_key: "model"
tag_value: "gradient_boosting Regressor"

module_name: "sklearn.ensemble"
class_name: "GradientBoostingRegressor"

params:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]