model_name: MLP
artifact_path: mlp_model

tag_key: "model"
tag_value: "MultiLayer Perceptron"

module_name: "src.nn"
class_name: "MLP"

optimizer:
  module_name: "torch.optim"
  class_name: "Adam"

has_embeds: False

params:
  module__input_size: [-1]  ### GETS OVERWRITTEN IN THE src/main.py
  module__output_size: [1]  
  module__hidden_units1: [128]
  module__hidden_units2: [64]
  module__hidden_units3: [32]
  module__seed: [88]
  max_epochs: [10, 20, 50]
  optimizer__lr: [1e-4, 3e-4, 0.001]
  optimizer__weight_decay: [1.0, 10.0, 100.0]
