model_name: MLP
artifact_path: mlp_model

tag_key: "model"
tag_value: "MultiLayer Perceptron"

module_name: "src.models"
class_name: "SimpleNN"

optimizer:
  module_name: "torch.optim"
  class_name: "Adam"

params:
  module__input_size: [-1]  ### GETS OVERWRITTEN IN THE src/main.py
  module__output_size: [1]  
  module__hidden_units1: [32, 64, 128]
  module__hidden_units2: [16, 32, 64]
  module__hidden_units3: [8, 16, 32]
  module__num_regions: [-1]
  module__regions_embed_dim: [10, 20, 50]
  module__region_idx: [0]
  module__seed: [88]
  max_epochs: [50]
  optimizer__lr: [0.001]
  optimizer__weight_decay: [1.0, 10.0, 100.0]
