defaults:
  - _self_

folds: 3

evaluation_metric: "rmse"
cv_evaluation_metric: "mean_test_rmse"

pyfunc_predict_fn: "predict"

metrics:
  rmse: "rmse"
  mae: "neg_mean_absolute_error"
  r2: "r2"
  mape: "neg_mean_absolute_percentage_error"
