hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params:
      +model: mlp
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task: []
  job:
    name: main
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: main
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/andrey/MLOps-Project
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/andrey/MLOps-Project/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
user_name: austinreese
dataset_name: craigslist-carstrucks-data
save_path: data/raw/vehicles.csv
sample_size: 0.2
sample_num: 2
data_version: 3
model:
  folds: 3
  evaluation_metric: neg_root_mean_squared_error
  cv_evaluation_metric: mean_test_neg_mean_absolute_error
  pyfunc_predict_fn: predict
  metrics:
    rmse: neg_root_mean_squared_error
    mae: neg_mean_absolute_error
    r2: r2
    mape: neg_mean_absolute_percentage_error
experiment_name: initial_experiment
run_name: multi_run
random_state: 88
cv_n_jobs: -1
train_data_version: '3'
test_data_version: '4'
data:
  target_cols:
  - price
  target_low: 1000
  target_high: 40000
  impute_most_frequent:
  - manufacturer
  - model
  - fuel
  - title_status
  - transmission
  - state
  impute_median:
  - year
  impute_mean:
  - odometer
  - lat
  - long
  - posting_date
  dt_feature:
  - posting_date
  periodic_transform:
    lat:
      offset: 90
      period: 180
    long:
      offset: 0
      period: 180
    posting_date_month:
      offset: 0
      period: 12
    posting_date_day:
      offset: 0
      period: 31
  min_max_scale:
  - year
  std_scale:
  - odometer
  ohe_cols:
  - title_status
  - transmission
  - fuel
  - state
  - manufacturer
  label_cols:
  - WMI
  - VDS
  - model
  - region
  drop_rows:
  - VIN
  drop_cols:
  - condition
  - cylinders
  - VIN
  - drive
  - size
  - type
  - paint_color
  - county
  - image_url
  - description
  - posting_date
  - id
  - url
  - region_url
  - lat
  - long
  - posting_date_month
  - posting_date_day
