ohe_cols:
- ohe__title_status_clean
- ohe__title_status_lien
- ohe__title_status_missing
- ohe__title_status_parts only
- ohe__title_status_rebuilt
- ohe__title_status_salvage
- ohe__transmission_automatic
- ohe__transmission_manual
- ohe__transmission_other
- ohe__fuel_diesel
- ohe__fuel_electric
- ohe__fuel_gas
- ohe__fuel_hybrid
- ohe__fuel_other
- ohe__state_ak
- ohe__state_al
- ohe__state_ar
- ohe__state_az
- ohe__state_ca
- ohe__state_co
- ohe__state_ct
- ohe__state_dc
- ohe__state_de
- ohe__state_fl
- ohe__state_ga
- ohe__state_hi
- ohe__state_ia
- ohe__state_id
- ohe__state_il
- ohe__state_in
- ohe__state_ks
- ohe__state_ky
- ohe__state_la
- ohe__state_ma
- ohe__state_md
- ohe__state_me
- ohe__state_mi
- ohe__state_mn
- ohe__state_mo
- ohe__state_ms
- ohe__state_mt
- ohe__state_nc
- ohe__state_nd
- ohe__state_ne
- ohe__state_nh
- ohe__state_nj
- ohe__state_nm
- ohe__state_nv
- ohe__state_ny
- ohe__state_oh
- ohe__state_ok
- ohe__state_or
- ohe__state_pa
- ohe__state_ri
- ohe__state_sc
- ohe__state_sd
- ohe__state_tn
- ohe__state_tx
- ohe__state_ut
- ohe__state_va
- ohe__state_vt
- ohe__state_wa
- ohe__state_wi
- ohe__state_wv
- ohe__state_wy
- ohe__manufacturer_acura
- ohe__manufacturer_alfa-romeo
- ohe__manufacturer_aston-martin
- ohe__manufacturer_audi
- ohe__manufacturer_bmw
- ohe__manufacturer_buick
- ohe__manufacturer_cadillac
- ohe__manufacturer_chevrolet
- ohe__manufacturer_chrysler
- ohe__manufacturer_datsun
- ohe__manufacturer_dodge
- ohe__manufacturer_ferrari
- ohe__manufacturer_fiat
- ohe__manufacturer_ford
- ohe__manufacturer_gmc
- ohe__manufacturer_harley-davidson
- ohe__manufacturer_honda
- ohe__manufacturer_hyundai
- ohe__manufacturer_infiniti
- ohe__manufacturer_jaguar
- ohe__manufacturer_jeep
- ohe__manufacturer_kia
- ohe__manufacturer_land rover
- ohe__manufacturer_lexus
- ohe__manufacturer_lincoln
- ohe__manufacturer_mazda
- ohe__manufacturer_mercedes-benz
- ohe__manufacturer_mercury
- ohe__manufacturer_mini
- ohe__manufacturer_mitsubishi
- ohe__manufacturer_nissan
- ohe__manufacturer_pontiac
- ohe__manufacturer_porsche
- ohe__manufacturer_ram
- ohe__manufacturer_rover
- ohe__manufacturer_saturn
- ohe__manufacturer_subaru
- ohe__manufacturer_tesla
- ohe__manufacturer_toyota
- ohe__manufacturer_volkswagen
- ohe__manufacturer_volvo
